#!/usr/bin/env python3
"""
Alignment Check Script for AstroPT

This script validates the alignment between image and spectrum embeddings
generated by a pre-trained AstroPT model. It loads a checkpoint, processes
the full Arrow dataset, and calculates the cosine similarity between
modalities.
"""

import inspect
import os
import sys
import torch
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from typing import Tuple, Any, List
from tqdm import tqdm

# Ensure local modules are found
sys.path.append(os.getcwd())

try:
    from astropt.model import GPT, GPTConfig, ModalityConfig, ModalityRegistry
    from astropt.euclid_desi_arrow_dataloader import EuclidDESIDatasetArrow
except ImportError as e:
    print(f"[CRITICAL] Error importing modules: {e}")
    sys.exit(1)

# Path Configuration
CKPT_PATH = "/home/valonso/iac18_aasensio_shared/euclid_q1_desi_dr1/maxime/ckpt_final.pt" 
DATA_DIR = "/home/valonso/iac18_aasensio_shared/euclid_dr1/processed_data_arrow"
OUT_DIR = "/home/valonso/iac18_mhuertas_shared/valonso/astroPT/logs/astropt_100M_250K_arrow_T1_20251214" 

# Device used
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 32 


def load_model_from_checkpoint(ckpt_path: str) -> Tuple[torch.nn.Module, Any]:
    """
    Loads the model architecture and weights.
    Based on checkpoint inspection: Spectra patch_size is 10.
    """
    print(f"[INFO] Loading model from {ckpt_path}...")
    checkpoint = torch.load(ckpt_path, map_location=DEVICE)
    
    # 1. Retrieve configuration
    conf_dict = checkpoint.get('config', checkpoint.get('model_args'))
    if conf_dict is None:
        raise ValueError("Configuration dictionary not found in checkpoint.")
    
    # Filter unexpected arguments
    valid_keys = set(inspect.signature(GPTConfig).parameters.keys())
    clean_conf = {k: v for k, v in conf_dict.items() if k in valid_keys}
    config = GPTConfig(**clean_conf)
    
    # 2. Instantiate Registry (MANUAL FIX BASED ON INSPECTION)
    if 'modality_registry' in checkpoint:
        registry = checkpoint['modality_registry']
    else:
        print("[WARNING] 'modality_registry' missing. Reconstructing based on checkpoint weights...")
        modalities = [
            ModalityConfig(
                name="images",
                input_size=1024,    # 16*16*4
                pos_input_size=196, # 224/16 = 14 -> 14^2 = 196 patches
                patch_size=16, 
                embed_pos=True,
                loss_weight=1.0
            ),
            ModalityConfig(
                name="spectra",
                input_size=10,       # INSPECTED: transformer.wte.spectra.c_fc.weight is [3072, 10]
                pos_input_size=1024, # INSPECTED: transformer.wpe.spectra.wpe.weight is [1024, 768]
                patch_size=10,       # Match input_size
                embed_pos=True,
                loss_weight=1.0
            )
        ]
        registry = ModalityRegistry(modalities)

    # 3. Instantiate model
    model = GPT(config, registry)
    
    # 4. Load weights
    state_dict = checkpoint['model']
    clean_sd = {
        k.replace('_orig_mod.', '').replace('module.', ''): v 
        for k, v in state_dict.items()
    }
    
    keys = model.load_state_dict(clean_sd, strict=False)
    print(f"[DEBUG] Missing keys: {len(keys.missing_keys)} | Unexpected keys: {len(keys.unexpected_keys)}")
    
    # Move to device and cast to BFloat16 to match data
    model.to(device=DEVICE)
    model.bfloat16()
    model.eval()
    return model, registry


def main() -> None:
    """
    Main execution routine.
    """
    # 1. Load Model
    try:
        model, registry = load_model_from_checkpoint(CKPT_PATH)
    except Exception as e:
        print(f"[FATAL] Could not load model. Error: {e}")
        return

    # 2. Load Dataset
    print("[INFO] Loading Arrow Dataset (Test Split)...")
    try:
        transforms = EuclidDESIDatasetArrow.data_transforms()
    except AttributeError:
        transforms = {} 

    ds = EuclidDESIDatasetArrow(
        arrow_folder_root=DATA_DIR,
        split="test",  
        modality_registry=registry,
        spiral=True,
        transform=transforms,
        stochastic=False 
    )

    if len(ds) == 0:
        print("[ERROR] Dataset is empty.")
        return

    dl = DataLoader(ds, batch_size=BATCH_SIZE, num_workers=1, shuffle=False)
    
    print(f"[INFO] Starting Full Evaluation on {len(ds)} galaxies...")
    all_sims: List[np.ndarray] = []

    for batch in tqdm(dl, desc="Processing Batches"):

            if batch['spectra'].shape[-1] > 7780:
                batch['spectra'] = batch['spectra'][..., :7780]

            batch_processed = EuclidDESIDatasetArrow.process_modes(batch, registry, DEVICE)
            inputs = batch_processed["X"]
            
            inputs['spectra'] = inputs['spectra'].reshape(-1, 778, 10)
            
            for key in inputs.keys():
                if "pos" in key:
                    if inputs[key].dim() > 2:
                        inputs[key] = inputs[key].flatten(1)
                    
                    if "spectra" in key:
                        inputs[key] = inputs[key][:, :778]
                    elif "images" in key:
                        inputs[key] = inputs[key][:, :196]
                    
                    inputs[key] = inputs[key].to(device=DEVICE, dtype=torch.long)
                    
            embeddings = model.get_embeddings(inputs)
            
            if 'images' not in embeddings or 'spectra' not in embeddings:
                continue
            
            emb_img_global = embeddings['images'].mean(dim=1)
            emb_spec_global = embeddings['spectra'].mean(dim=1)
            
            sim = F.cosine_similarity(emb_img_global, emb_spec_global, dim=1)
            all_sims.append(sim.detach().to(torch.float32).cpu().numpy())

    # 3. Process Results
    if not all_sims:
        print("[ERROR] No similarities were calculated.")
        return

    all_sims_concat = np.concatenate(all_sims)
    
    mean_sim = np.mean(all_sims_concat)
    median_sim = np.median(all_sims_concat)
    min_sim = np.min(all_sims_concat)
    max_sim = np.max(all_sims_concat)
    
    print(f"\nFULL TEST SET RESULTS (N={len(all_sims_concat)})")
    print("-" * 40)
    print(f"Mean Similarity:   {mean_sim:.4f}")
    print(f"Median Similarity: {median_sim:.4f}")
    print(f"Minimum: {min_sim:.4f} | Maximum: {max_sim:.4f}")
    
    # Plotting
    plt.figure(figsize=(10, 6))
    plt.hist(all_sims_concat, bins=50, color='royalblue', edgecolor='black', alpha=0.7)
    plt.axvline(mean_sim, color='red', linestyle='dashed', linewidth=2, label=f'Mean: {mean_sim:.2f}')
    plt.axvline(median_sim, color='orange', linestyle='dotted', linewidth=2, label=f'Median: {median_sim:.2f}')
    plt.title(f"Image-Spectrum Alignment on Full Test Set ({len(ds)} galaxies)")
    plt.xlabel("Cosine Similarity")
    plt.ylabel("Count")
    plt.legend()
    plt.grid(alpha=0.3)
    
    output_plot = f"{OUT_DIR}/full_alignment_test.png"
    plt.savefig(output_plot)
    print(f"[INFO] Plot saved to '{output_plot}'")

    print("-" * 40)
    if mean_sim > 0.8:
        print("[DIAGNOSIS] EXCELLENT.")
    elif mean_sim > 0.5:
        print("[DIAGNOSIS] MODERATE.")
    else:
        print("[DIAGNOSIS] POOR.")
    print("-" * 40)

if __name__ == "__main__":
    main()