"""
AstroPT Latent Mapper Dashboard Generator.

Reads directories containing multiple CSV files generated by the probing_latent_mapper.py,
aggregates them per training run, and generates comparative dashboards.

Author: Victor Alonso Rodriguez
Date: March 2026
"""

import argparse
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from typing import List, Optional

# Expected X-axis categories in strict order for mappings. 
"""
AstroPT Latent Mapper Dashboard Generator.

Reads directories containing multiple CSV files generated by the probing_latent_mapper.py,
aggregates them per training run, and generates comparative dashboards.

Author: Victor Alonso Rodriguez
Date: March 2026
"""

import argparse
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from typing import List, Optional

# Expected X-axis categories in strict order for mappings
CONFIG_ORDER = [
    'images->joint (Zero-Shot)', 
    'images->joint (MLP)', 
    'images->spectra (Zero-Shot)',
    'images->spectra (MLP)',
    'spectra->joint (Zero-Shot)',
    'spectra->joint (MLP)',
    'spectra->images (Zero-Shot)',
    'spectra->images (MLP)',
    'joint->images (Zero-Shot)',
    'joint->images (MLP)', 
    'joint->spectra (Zero-Shot)',
    'joint->spectra (MLP)'
]

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate performance dashboards for latent mapping tasks.")
    
    parser.add_argument("--save_dir", type=str, required=True, help="Plot Saving Directory")
    parser.add_argument('--save_name', default="mapper_dashboard", help="Saving optional name")
    
    parser.add_argument('--input_dirs', nargs='+', required=True, help="Paths to the latent_mapper directories to compare.")
    parser.add_argument('--names', nargs='+', help="Names of the training runs for the legend (must match number of directories).")
    parser.add_argument('--targets', nargs='+', required=True, help="List of targets to plot (e.g., Z SPECTYPE HALPHA_FLUX).")
    
    return parser.parse_args()

def load_and_merge_data(dirpaths: List[str | Path], test_names: Optional[List[str]] = None) -> pd.DataFrame:
    """
    Scans directories for Mapper CSVs, merges all mappings found in a directory 
    under the same Test_Name, and concatenates everything.
    """
    if test_names is None or len(test_names) != len(dirpaths):
        test_names = [f"Run {i+1}" for i in range(len(dirpaths))]

    df_list = []
    for dirpath, name in zip(dirpaths, test_names):
        dirpath = Path(dirpath)
        
        csv_files = list(dirpath.glob("mapper_*.csv"))
        if not csv_files:
            print(f"[WARNING] No mapper_*.csv files found in {dirpath}. Skipping.")
            continue
            
        for filepath in csv_files:
            try:
                df = pd.read_csv(filepath)
                # Clean empty rows
                df = df.dropna(subset=['Target', 'Task'])
                
                df['Test_Name'] = name
                df['Config'] = df['Mapping'] 
                df_list.append(df)
            except Exception as e:
                print(f"[ERROR] Could not read {filepath}: {e}")

    if not df_list:
        raise ValueError("No valid CSV files were loaded from any directory.")

    return pd.concat(df_list, ignore_index=True)

def generate_dashboard(df: pd.DataFrame, task_type: str, targets: List[str], save_dir: str | Path, save_name: str) -> None:
    if not targets:
        return

    task_df = df[(df['Task'].str.lower() == task_type.lower()) & (df['Target'].isin(targets))].copy()
    
    if task_df.empty:
        return

    task_df = task_df.dropna(axis=1, how='all')

    metadata_cols = ['Target', 'Task', 'Mapping', 'k_Neighbors', 'Test_Name', 'Config']
    metrics = [col for col in task_df.columns if col not in metadata_cols and pd.api.types.is_numeric_dtype(task_df[col])]
    
    n_rows = len(targets)
    n_cols = len(metrics)

    if n_cols == 0:
        print(f"[WARNING] No numeric metrics found for {task_type}. Skipping dashboard.")
        return

    fig, axes = plt.subplots(nrows=n_rows, ncols=n_cols, figsize=(4 * n_cols, 4 * n_rows), squeeze=False)

    tests = task_df['Test_Name'].unique()
    colors = ["black", "red", "mediumseagreen", "dodgerblue", "darkorchid", "darkorange", "saddlebrown"]
    markers = ['.', '*', 'v', 'P', 's', 'X', 'D']
    sizes = ['10', '9', '8', '8', '7', '8', '7']

    available_configs = [c for c in CONFIG_ORDER if c in task_df['Config'].unique()]
    missing_configs = [c for c in task_df['Config'].unique() if c not in available_configs]
    final_config_order = available_configs + sorted(missing_configs)

    for i, target in enumerate(targets):
        target_df = task_df[task_df['Target'] == target]
        
        for j, metric in enumerate(metrics):
            ax = axes[i, j]
            
            for test_idx, test_name in enumerate(tests):
                test_df = target_df[target_df['Test_Name'] == test_name].copy()
                
                test_df['Config'] = pd.Categorical(test_df['Config'], categories=final_config_order, ordered=True)
                test_df = test_df.sort_values('Config')
                
                ax.plot(
                    test_df['Config'], 
                    test_df[metric], 
                    marker=markers[test_idx % len(markers)], 
                    linestyle='--', 
                    linewidth=0.5,
                    markersize=sizes[test_idx % len(sizes)],
                    alpha=0.5,
                    label=test_name, 
                    color=colors[test_idx % len(colors)]
                )

            # Formatting the subplot
            ax.set_title(f'{target} - {metric}')
            ax.set_xticks(range(len(final_config_order)))
            ax.set_xticklabels(final_config_order, rotation=45, ha='right')
            ax.grid(True, linestyle='-', alpha=0.4)
            
            if j == 0:
                ax.set_ylabel('Score / Value', fontsize=12)

    fig_height = fig.get_figheight()
    
    title_offset_inches = 0.5    
    legend_offset_inches = 0.9   
    header_space_inches = 1.6
    
    title_y = 1.0 - (title_offset_inches / fig_height)
    legend_y = 1.0 - (legend_offset_inches / fig_height)
    top_limit = 1.0 - (header_space_inches / fig_height)
    
    plt.tight_layout(rect=[0, 0, 1, top_limit])

    fig.suptitle(f'Latent Mapper Performance Comparison: {task_type.capitalize()}', 
                 fontsize=20, y=title_y, va='top')
    
    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.legend(handles, labels, loc='upper center', ncol=min(len(tests), 4), 
               fontsize=12, bbox_to_anchor=(0.5, legend_y), frameon=True)
    
    prefix = save_name or "mapper_dashboard"
    save_name_dash = f"{prefix}_{task_type}.png"
    save_path = Path(save_dir) / save_name_dash
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"[INFO] {task_type.capitalize()} Dashboard saved successfully at: {save_dir}")

def main():
    args = parse_args()

    save_dir = Path(args.save_dir) / "latent_mapper"
    save_dir.mkdir(parents=True, exist_ok=True)
    
    dir_paths_list = [Path(p) for p in args.input_dirs]

    try:
        df = load_and_merge_data(dir_paths_list, args.names)
    except Exception as e:
        print(f"[FATAL ERROR] Failed to load data: {e}")
        return

    requested_targets = set(args.targets)
    
    regression_targets = df[(df['Task'] == 'regression') & (df['Target'].isin(requested_targets))]['Target'].unique().tolist()
    classification_targets = df[(df['Task'] == 'classification') & (df['Target'].isin(requested_targets))]['Target'].unique().tolist()
    
    found_targets = set(regression_targets + classification_targets)
    missing_targets = requested_targets - found_targets
    if missing_targets:
        print(f"[WARNING] The following requested targets were not found in the data: {missing_targets}")

    generate_dashboard(df, 'regression', regression_targets, save_dir, args.save_name)
    generate_dashboard(df, 'classification', classification_targets, save_dir, args.save_name)

if __name__ == "__main__":
    main()

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate performance dashboards for latent mapping tasks.")
    
    parser.add_argument("--save_dir", type=str, required=True, help="Plot Saving Directory")
    parser.add_argument('--save_name', default="mapper_dashboard", help="Saving optional name")
    
    parser.add_argument('--input_dirs', nargs='+', required=True, help="Paths to the latent_mapper directories to compare.")
    parser.add_argument('--names', nargs='+', help="Names of the training runs for the legend (must match number of directories).")
    parser.add_argument('--targets', nargs='+', required=True, help="List of targets to plot (e.g., Z SPECTYPE HALPHA_FLUX).")
    
    return parser.parse_args()

def load_and_merge_data(dirpaths: List[str | Path], test_names: Optional[List[str]] = None) -> pd.DataFrame:
    """
    Scans directories for Mapper CSVs, merges all mappings found in a directory 
    under the same Test_Name, and concatenates everything.
    """
    if test_names is None or len(test_names) != len(dirpaths):
        test_names = [f"Run {i+1}" for i in range(len(dirpaths))]

    df_list = []
    for dirpath, name in zip(dirpaths, test_names):
        dirpath = Path(dirpath)
        
        csv_files = list(dirpath.glob("mapper_*.csv"))
        if not csv_files:
            print(f"[WARNING] No mapper_*.csv files found in {dirpath}. Skipping.")
            continue
            
        for filepath in csv_files:
            try:
                df = pd.read_csv(filepath)
                # Clean empty rows
                df = df.dropna(subset=['Target', 'Task'])
                
                df['Test_Name'] = name
                df['Config'] = df['Mapping'] 
                df_list.append(df)
            except Exception as e:
                print(f"[ERROR] Could not read {filepath}: {e}")

    if not df_list:
        raise ValueError("No valid CSV files were loaded from any directory.")

    return pd.concat(df_list, ignore_index=True)

def generate_dashboard(df: pd.DataFrame, task_type: str, targets: List[str], save_dir: str | Path, save_name: str) -> None:
    if not targets:
        return

    task_df = df[(df['Task'].str.lower() == task_type.lower()) & (df['Target'].isin(targets))].copy()
    
    if task_df.empty:
        return

    task_df = task_df.dropna(axis=1, how='all')

    metadata_cols = ['Target', 'Task', 'Mapping', 'k_Neighbors', 'Test_Name', 'Config']
    metrics = [col for col in task_df.columns if col not in metadata_cols and pd.api.types.is_numeric_dtype(task_df[col])]
    
    n_rows = len(targets)
    n_cols = len(metrics)

    if n_cols == 0:
        print(f"[WARNING] No numeric metrics found for {task_type}. Skipping dashboard.")
        return

    fig, axes = plt.subplots(nrows=n_rows, ncols=n_cols, figsize=(4 * n_cols, 4 * n_rows), squeeze=False)

    tests = task_df['Test_Name'].unique()
    colors = ["black", "red", "mediumseagreen", "dodgerblue", "darkorchid", "darkorange", "saddlebrown"]
    markers = ['.', '*', 'v', 'P', 's', 'X', 'D']
    sizes = ['10', '9', '8', '8', '7', '8', '7']

    available_configs = [c for c in CONFIG_ORDER if c in task_df['Config'].unique()]
    missing_configs = [c for c in task_df['Config'].unique() if c not in available_configs]
    final_config_order = available_configs + sorted(missing_configs)

    for i, target in enumerate(targets):
        target_df = task_df[task_df['Target'] == target]
        
        for j, metric in enumerate(metrics):
            ax = axes[i, j]
            
            for test_idx, test_name in enumerate(tests):
                test_df = target_df[target_df['Test_Name'] == test_name].copy()
                
                test_df['Config'] = pd.Categorical(test_df['Config'], categories=final_config_order, ordered=True)
                test_df = test_df.sort_values('Config')
                
                ax.plot(
                    test_df['Config'], 
                    test_df[metric], 
                    marker=markers[test_idx % len(markers)], 
                    linestyle='--', 
                    linewidth=0.5,
                    markersize=sizes[test_idx % len(sizes)],
                    alpha=0.5,
                    label=test_name, 
                    color=colors[test_idx % len(colors)]
                )

            # Formatting the subplot
            ax.set_title(f'{target} - {metric}')
            ax.set_xticks(range(len(final_config_order)))
            ax.set_xticklabels(final_config_order, rotation=45, ha='right')
            ax.grid(True, linestyle='-', alpha=0.4)
            
            if j == 0:
                ax.set_ylabel('Score / Value', fontsize=12)

    fig_height = fig.get_figheight()
    
    title_offset_inches = 0.5    
    legend_offset_inches = 0.9   
    header_space_inches = 1.6
    
    title_y = 1.0 - (title_offset_inches / fig_height)
    legend_y = 1.0 - (legend_offset_inches / fig_height)
    top_limit = 1.0 - (header_space_inches / fig_height)
    
    plt.tight_layout(rect=[0, 0, 1, top_limit])

    fig.suptitle(f'Latent Mapper Performance Comparison: {task_type.capitalize()}', 
                 fontsize=20, y=title_y, va='top')
    
    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.legend(handles, labels, loc='upper center', ncol=min(len(tests), 4), 
               fontsize=12, bbox_to_anchor=(0.5, legend_y), frameon=True)
    
    prefix = save_name or "mapper_dashboard"
    save_name_dash = f"{prefix}_{task_type}.png"
    save_path = Path(save_dir) / save_name_dash
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"[INFO] {task_type.capitalize()} Dashboard saved successfully at: {save_dir}")

def main():
    args = parse_args()

    save_dir = Path(args.save_dir) / "latent_mapper"
    save_dir.mkdir(parents=True, exist_ok=True)
    
    dir_paths_list = [Path(p) for p in args.input_dirs]

    try:
        df = load_and_merge_data(dir_paths_list, args.names)
    except Exception as e:
        print(f"[FATAL ERROR] Failed to load data: {e}")
        return

    requested_targets = set(args.targets)
    
    regression_targets = df[(df['Task'] == 'regression') & (df['Target'].isin(requested_targets))]['Target'].unique().tolist()
    classification_targets = df[(df['Task'] == 'classification') & (df['Target'].isin(requested_targets))]['Target'].unique().tolist()
    
    found_targets = set(regression_targets + classification_targets)
    missing_targets = requested_targets - found_targets
    if missing_targets:
        print(f"[WARNING] The following requested targets were not found in the data: {missing_targets}")

    generate_dashboard(df, 'regression', regression_targets, save_dir, args.save_name)
    generate_dashboard(df, 'classification', classification_targets, save_dir, args.save_name)

if __name__ == "__main__":
    main()